add sftpgo builder
threefoldtech/builders pull request #60
Opened 2023-10-10 11:26 UTC by rawdaGastan

### Issues

- https://github.com/threefoldtech/3bot/issues/166

### problems 

- can't run any example
- crystallib docker can't be imported

2023-10-12 07:36 UTC, Omarabdul3ziz requested changes
small comment

2023-10-12 07:36 UTC, Omarabdul3ziz commented on builders/play/sftpgo/sftpgo.v
> +	r.add_run(
there is two useful recipes for zinit:
`add_zinit`: will install zinit and make it the entrypoint
`add_zinit_cmd`: that can create zinit services files without needing to copy the files

2023-10-12 15:08 UTC, rawdaGastan commented on builders/play/sftpgo/sftpgo.v
> +	r.add_run(
I tried it but it fails because it needs alpine and onyloffice image doesn't have it :((

2023-10-16 08:31 UTC, Omarabdul3ziz approved these changes

2023-10-16 10:39 UTC, merged